//! Generates the built-in skill registry: one `(file stem, include_str! path)`
//! entry per `*.md` in `src/templates/skills/`, emitted to
//! `OUT_DIR/builtin_skills.rs` and pulled into `skills.rs` via `include!`.
//! Adding a built-in skill is adding a file — no Rust wiring to touch.

use std::{env, fs, path::Path};

fn main() {
    let dir = Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("src")
        .join("templates")
        .join("skills");
    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("builtin_skills.rs");

    // Rebuild when a skill file is added, removed or edited. The directory
    // line covers additions/removals; the per-file lines cover edits.
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut files: Vec<String> = fs::read_dir(&dir)
        .map(|rd| {
            rd.filter_map(Result::ok)
                .filter(|e| e.path().extension().is_some_and(|x| x == "md"))
                .map(|e| e.file_name().to_string_lossy().into_owned())
                .collect()
        })
        .unwrap_or_default();
    files.sort();

    let mut code = String::from("// Generated by build.rs — do not edit.\n");
    code.push_str("/// `(file stem, source)` for every built-in skill template.\n");
    code.push_str("pub(crate) static SKILL_FILES: &[(&str, &str)] = &[\n");
    for file in &files {
        let stem = file.strip_suffix(".md").unwrap_or(file);
        let path = dir.join(file).to_string_lossy().into_owned();
        code.push_str(&format!("    ({stem:?}, include_str!({path:?})),\n"));
        println!("cargo:rerun-if-changed={path}");
    }
    code.push_str("];\n");

    fs::write(&out, code).expect("write OUT_DIR/builtin_skills.rs");
}
